### PR TITLE
[IMP] base: Fixed state code based in SAT catalog

### PR DESCRIPTION
**Pull request by luistorresm**
The SAT provide this catalog to state codes:
http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Complementoscfdi/catNomina.xls

This attribute is required in payroll [v1.2](http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Complementoscfdi/nomina12.pdf).

Atributo requerido para expresar la clave de la entidad
federativa en donde el receptor del recibo prestó el servicio.

### CODE REVIEW

**Comment by luistorresm** [comment]
@moylop260 

What do you think about this change?

The payroll require this state code, do you think that we could change the state code?

Regards

**Comment by moylop260** [comment]
👍 
Ese campo siempre era un misterio porque hay como 3 diferentes convenciones.
Que bueno que ya proporcionaron la oficial.

**Comment by moylop260** [comment]
Duda: Es necesario mezclarlo aquí o podemos esperar la gestión de una PR a odoo/odoo?

**Comment by luistorresm** [comment]
En México-10 se esta utilizando este repo

Pero voy a hacer esta PR para Odoo, y si nos lo mergean lo paso con cherry-pick a la version de Odoo.

Gracias

**Comment by luistorresm** [comment]
Odoo PR https://github.com/odoo/odoo/pull/15535

**Comment by nhomar** [comment]
can you make this PR to odoo/odoo v10.0 please?

**Comment by luistorresm** [comment]
@nhomar 

Odoo PR https://github.com/odoo/odoo/pull/15535

**Comment by luistorresm** [comment]
Changed by cherry-pick in https://github.com/Vauxoo/odoo/pull/179

**Comment by nhomar** [comment]
On Fri, Feb 17, 2017 at 9:21 AM, Luis Ernesto Torres Macías <
notifications@github.com> wrote:

> Changed by cherry-pick in #179 <https://github.com/Vauxoo/odoo/pull/179>
>

make a full PR please of v10

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Pull request closed without merging**
