### PR TITLE
[10.0] Merge from odoo/10.0

### PR DESCRIPTION
**Pull request by jorgescalona**
`git rebase -i --autosquash odoo/10.0`

### CODE REVIEW

**Comment by JulioSerna** [comment]
@moylop260 

Could you check/merge this pr?

**Comment by moylop260** [comment]
Could you create dummy PR for main projects?
(Ask @dsabrinarg and @luistorresm  about)

**Comment by jorgescalona** [comment]
> Could you create dummy PR for main projects?
> (Ask @dsabrinarg and @luistorresm about)

@moylop260 @luistorresm the dummy prs are made one towards a repo of peru and another to a repo of mx can check please!

**Comment by luistorresm** [comment]
Dummy PRs 👍

**Comment by moylop260** [comment]
@dsabrinarg are you agree?

**Comment by dsabrinarg** [comment]
@moylop260 @JulioSerna @luistorresm cherry-pick applies only for V 9.0 because we have only one customer on that version an is being migrated, for other versions please until the team agree otherwise, set a pull from odoo/odoo fro vauxoo/odoo

@nhomar as far as I remember, this was mentioned by you, are we agree or I'm making a wrong statement?

BTW, we have other cherry-pick already merged on 10.0 :-(

**Comment by nhomar** [comment]
why not update all?

**Comment by jorgescalona** [comment]
@moylop260 both rebuilds were satisfactory with respect to the dummys

**Comment by moylop260** [comment]
Merged directly because this is a rebase with all changes from odoo/odoo@10.0

**Pull request closed without merging**
