### PR TITLE
8.0 translate truiz

### PR DESCRIPTION
**Pull request by ruiztulio**
Fixes Export translation bug, req by @zaoral

### CODE REVIEW

**Comment by zaoral** [comment]
Thank you @ruiztulio 
I waiting for runbot checks the next instances:

- http://runbot.vauxoo.com/runbot/team/yoytec-24#48pull_51
- http://runbot.vauxoo.com/runbot/team/lodi-21#46pull_51
- http://runbot.vauxoo.com/runbot/team/vauxoo-20#64pull_51
- http://runbot.vauxoo.com/runbot/team/rma-34#74pull_51
- http://runbot.vauxoo.com/runbot/team/lodi-21?testing=1&running=1&done=1&limit=10000&pending=1#83pull_51

I will do the feedback with the result soon

**Comment by zaoral** [comment]
@ruiztulio I check the runbot and everything looks good.
lodi and yoytec builds show warnings but is something external to the change,

This PR is ready to merge.
Regards.

**Comment by nhomar** [comment]
@zaoral 

Please Kath, on this PR there is at least 5 changes that may affect functinally which is lready in production:

@wtaferner 	[FIX] product_extended: cost price computation from BOM … 
@guewen 	[IMP] purchase: Purchase report uses the state of lines instead of pu… …
@guewen 	[IMP] purchase: Ignore canceled purchase lines … 
@lepistone 	[FIX] stock: propagate owner when generating extra move
@clonedagain 	[FIX] product: Don't force arbitrary precision on weights … 

Can you make a functional test (manual) on a testing enviroment with lodi and yoytec in order to be sure all process is Ok!

@dsabrinarg Please can you help to Kathy to do the job on Lodi with Kath.

Regards.

**Comment by lepistone** [comment]
FYI my commit above fixes a very specific corner case: in the transfer picking wizard, if you increase the quantity, and you specify an owner in the operation line, an extra move will be created. With the fix, the new move receives the same owner from the operation line.

**Comment by nhomar** [comment]
@lepistone thanks for the input, @josemoralep please check this use case with @zaoral

**Comment by zaoral** [comment]
@nhomar ok. will start to the check.

**Pull request merged**
