### PR TITLE
Revert "[8.0][REF] hr_payroll_account: Add fields.function partner_id Reverts Vauxoo/odoo#3

### PR DESCRIPTION
**Pull request by jorgenaranjoVauxoo**

### CODE REVIEW

**Comment by nhomar** [comment]
@moylop260 @jorgenaranjo puedo mergear ésto?

**Comment by moylop260** [comment]
First we need a merge of a backport from odoo/odoo
@jorgenaranjo,
Can you add a link to other PR to merge it together?

**Comment by jorgenaranjo** [comment]
https://github.com/Vauxoo/odoo/pull/59

**Comment by moylop260** [comment]
@jorgenaranjo
Can you add print-screen of runbot's results?

**Comment by nhomar** [comment]
@moylop260 is this valid?

**Pull request closed without merging**
