### PR TITLE
8.0 merge from odoo dev karen

### PR DESCRIPTION
**Pull request by KarenKawaii**
## ToDo:

**Dummy PRs to projects:**

- [x] yoytec: https://github.com/Vauxoo/yoytec/pull/1611
- [x] lodigroup: https://github.com/Vauxoo/lodigroup/pull/587
- [x] oml-v2: https://github.com/Vauxoo/odoo-mexico-v2/pull/357

### CODE REVIEW

**Comment by KarenKawaii** [comment]
Hi @moylop260 this is the PR to update vauxoo-odoo/8.0 in base of odoo/8.0

I attach the latest full logs for runbot builds of the PR dummies in the description with the following resume:

- [yoytec full all logs] (http://runbot.vauxoo.com/runbot/static/build/13709-1611-59b57e/logs/job_20_test_all.txt) The latest runbot build is green.
- [lodigroup full all logs] (http://runbot.vauxoo.com/runbot/static/build/13725-587-c45044/logs/job_20_test_all.txt) The latest runbot is yellow with warnings not related to this changes.
- [odoo-mexico-v2 full all logs] (http://runbot.vauxoo.com/runbot/static/build/13713-357-60133f/logs/job_20_test_all.txt) The latest runbot build is green.

**Comment by nhomar** [comment]
@KarenKawaii You conclusions about tests?

**Comment by KarenKawaii** [comment]
@nhomar the last time that I prove this branch in the PR dummies the tests run correctly.

However if @moylop260 thought that the commit https://github.com/odoo/odoo/commit/f02b23006b63c375258cf5a33c903318e59e7bbb (probably) solves the issue https://github.com/Vauxoo/yoytec/issues/1317 in yoytec, well is not solve.
You can check the PR in addons-vauxoo: https://github.com/Vauxoo/addons-vauxoo/pull/1009 with the PR dummy in yoytec: https://github.com/Vauxoo/yoytec/pull/1618

Regards.

**Comment by nhomar** [comment]
can you rerun the tests and instance by instance put here the results please, updateing your branch to the very last odoo version.

Then inmediatly it finish put here the results.

**Comment by KarenKawaii** [comment]
Roger that.

**Comment by KarenKawaii** [comment]
Hi @nhomar this are the results after update the odoo branch and rebuild the tests:

#### Lodigroup and odoo-mexico-v2:

- Lodigroup [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/13965-587-fda858/logs/job_20_test_all.txt) There is an error related to the finkok pac in runbot tests.
- Odoo-mexico-v2 [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/13964-357-82a96f/logs/job_20_test_all.txt) The same error as above in finkok pac in runbot tests.

**Note:**
The error happens too in a rebuild in the branch 8.0 oml-2 instance that was green at merge:
- Odoo-mexico-v2 [8.0 branch rebuild full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/13969-8-0-314aec/logs/job_20_test_all.txt)

 So, I think this error is related to the PAC itself (the hour at the night when we are running the tests  using the PAC's testing environment) and not to the new changes in this PR.

#### Yoytec:
- Yoytec [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/13955-1611-6d047a/logs/job_20_test_all.txt) The tests are green in runbot.


**As a comment to let you know**
The PR in addons-vauxoo https://github.com/Vauxoo/addons-vauxoo/pull/1009 to revert the workaround in order to fix the issue in yoytec https://github.com/Vauxoo/yoytec/issues/1317 is red in runbot (PR dummy).
So the PR in addons-vauxoo is not able to merge yet because the latest updates in odoo don't solve this problem. Appart of that I think this PR to update vauxoo/odoo is fine.

Regards.

**Comment by KarenKawaii** [comment]
Hi @nhomar and @moylop260 what do you think about the results?

Let me know.

**Comment by moylop260** [comment]
Maybe we could merge this one because you have created the work of update fine!

**Comment by KarenKawaii** [comment]
@moylop260 I think this PR is mergeable. 

The PR that I don't think is mergeable yet is the PR reverting a commit in addons-vauxoo, as you can see in my comment https://github.com/Vauxoo/odoo/pull/103#issuecomment-230979919 the runbot in yoytec's pr dummy is red.

**Comment by KarenKawaii** [comment]
Hi @nhomar and @moylop260 I update the branch with the latest changes in odoo/8.0

These are the new results:

- odoo-mexico-v2 [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/14209-357-82a96f/logs/job_20_test_all.txt) The only error is with the finkok PAC in a test. However, I made a functional test to prove the pac and everything works fine when I stamped an invoice:
invoice-signed-finkok

- lodigroup [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/14210-587-fda858/logs/job_20_test_all.txt) The same error as above.
I made the same test like in odoo-mexico-v2 and everything works fine:
invoice signed finkok apex

- yoytec [full-all-logs] (http://runbot.vauxoo.com/runbot/static/build/14206-1611-a978c2/logs/job_20_test_all.txt) Everything was ok.

So, could you review/merge this PR please?

**Comment by nhomar** [comment]
@josemoralesp @dsabrinarg Can you xcheck the funcional impact of this merge?

In order to uupdate everything.

**Comment by josemoralesp** [comment]
:+1:  The code review and functional test

**Comment by KarenKawaii** [comment]
Thanks @josemoralesp 

So @dsabrinarg , @moylop260 and @nhomar do you think this PR is ready to be merge?

**Comment by dsabrinarg** [comment]
@moylop260 @KarenKawaii @josemoralesp @nhomar LGTM

**Pull request merged**
