### PR TITLE
[FIX] the task form view now show the name field in the complete long of the sheet, before was showing only the half of the space, this because the kanban_state field was added and was generating split the grid space. Fix Vauxoo/instance-vauxoo-com#62

### PR DESCRIPTION
**Pull request by zaoral**
Task [vx#3781](https://www.vauxoo.com/web#id=3781&view_type=form&model=project.task&action=138)

Resullt:
image

### CODE REVIEW

**Comment by zaoral** [comment]
Waiting for testing tools results.

**Comment by zaoral** [comment]
This PR Fix Vauxoo/instance-vauxoo-com#62

**Comment by zaoral** [comment]
Waiting result from testing tool.
Only runbot
http://runbot.vauxoo.com/runbot/team/vauxoo-20#05720-61-8-0-er

**Comment by zaoral** [comment]
@nhomar This PR is ready to review.

The runbot result is a Red for external reasons. But the modifcated module (project) install propertly as you can see in this error [log](http://runbot.vauxoo.com/runbot/static/build/05720-61-8-0-er/logs/job_20_test_all.txt)

Regrads.

**Comment by nhomar** [comment]
@zaoral 

At least the vulcano is on fire and no there are other solution than patch, then for such kind of fixes you should always use a PR with an external module.

Can you solve this in user_story module pliz?

**Comment by zaoral** [comment]
@nhomar got it. I will made the change in user_story module and will send you the new PR to review.

**Pull request closed without merging**
