### PR TITLE
[IMP]allow show user name when containts special characters

### PR DESCRIPTION
**Pull request by JulioSerna**

### CODE REVIEW

**Comment by moylop260** [comment]
@nhomar 
Can you give your feedback, please?

**Comment by nhomar** [comment]
Hola.

@JulioSerna  I can't see any reference to this solution related to odoo itself (the core repository) in order to ensure the correct approach.

1.- PR to Odoo.
2.- Ticket on Enterprise.

... in the mean time (just until Odoo approve/disaprove)
3.- PR to vauxoo/odoo.
4.- Execute PR with explícit reference to odoo/odoo issue.

Thanks.

**Comment by JulioSerna** [comment]
@nhomar @moylop260 

I'm going to try to explain better what happened,
already exist the bug reported, in this bug attached on MP,
[Bug reported in Launchpad](https://bugs.launchpad.net/openobject-server/+bug/1272610)

The MP has one "approve" but never was merged,
[MP to resolved bug(above)](https://code.launchpad.net/~cv.clearcorp/openobject-server/7.0-lp1272610-mail_sender_name/+merge/203200)

and in fact, I used that MP to our PR **adding to visibility of the email of user**

Odoo made one fix with reference the bug reported,
[Commit Odoo](https://github.com/odoo/odoo/commit/f2cf6ced17d3477b8858e3a8f955a42cc8a629ff#diff-69803ab75cb1ad2151941f12444d7510)

After they reversed the commit,
[Rev commit Odoo](https://github.com/odoo/odoo/commit/1b49a876196de1f4b6568ff1751f7c7c6b2d5002#diff-69803ab75cb1ad2151941f12444d7510)

Knowing this once, I continue with your 4 point mentioned above?

If I make one PR **only** to solve the bug(Special characters) would be exactly this MP(of clearcorp),
[MP to recolved bug(above)](https://code.launchpad.net/~cv.clearcorp/openobject-server/7.0-lp1272610-mail_sender_name/+merge/203200)

Know what I mean?

**Comment by moylop260** [comment]
@JulioSerna 
Ok, I got it.
I understand that this patch fix `unicode characters` but make a new issue with multiple addresses (comma separated).
But really we don't have a fix of `unicode characters` because we have this issue yet.
Can you create a new issue (add a comment with link here) and OPW ticket to wait answer from odony, please?

**Comment by JulioSerna** [comment]
Close this PR, because the bug was solved by Odoo,
we thought have the same bug, but this happened in users with "Alias" wrong,
for example in user test:
Loing = test@mycompany.com
user name = User test
Alias(wrong) = test@mycompany.com@domaincompany.com
Alias should be only = test@domaincompany.com

Details in task vauxoo #3527

**Pull request closed without merging**
