### PR TITLE
[REF] odoo: Update Vauxoo/odoo 10.0

### PR DESCRIPTION
**Pull request by maitaoriana**

### CODE REVIEW

**Comment by maitaoriana** [comment]
Hello @suniagajose, Could you review this PR? This is dummy for [rico](url). Thanks

**Comment by dsabrinarg** [comment]
This PR must be merged also https://github.com/Vauxoo/enterprise/pull/141

**Comment by maitaoriana** [comment]
With this update Vauxoo/Mexico is in red by this [test](https://github.com/Vauxoo/mexico/blob/10.0/l10n_mx_base/tests/test_account_invoice.py#L373), this is caused by this commit https://github.com/odoo/odoo/commit/6981320d017db77fc1c78cc4c522b9e31f46baad . That is why it is necessary to reverse commit after this merge. Issue a odoo: https://github.com/odoo/odoo/issues/18447

**Comment by dsabrinarg** [comment]
@moylop260 as soon as you merge this I will create the PR with the revert of the commit that is leading to a red at mexico repository, but please merge this.

**Comment by dsabrinarg** [comment]
@moylop260 FYI all the leader with project on this version gave their approval for their projects, [this](https://docs.google.com/spreadsheets/d/1jjW_EnehYrpKeCLKrbDdUggAfQyLz1M90mMdavvFKS0/edit?ts=596e1818#gid=1604842074) is the document where the approvals where recollected.

**Pull request merged**
