### PR TITLE
[10.0] odoo: Fix check_vat method - Proposal #2

### PR DESCRIPTION
**Pull request by Batuto**
#### In order to solve:
https://github.com/Vauxoo/odoo-peru/issues/217

#### And get the next line correct:
https://github.com/Vauxoo/odoo/blob/10.0/addons/base_vat/models/res_partner.py#L117

##### Résumé:
The `check_vat` method calls with one argument the `_construct_constraint_msg` method that receives no arguments, this leads an error.

### CODE REVIEW

**Comment by osvalr** [comment]
this cannot used into 10.0 because older API version

**Comment by moylop260** [comment]
You have a wrong cherry-pick
Could you repeat the process, please?

Your commit told us that you want to get the following commit:
https://github.com/odoo/odoo/commit/a7250766dc0d57a5d9e81825e69ee28fd0554fa6#diff-5818ba1e95e0716e509401478e1aacc8

But the diff is very very different to this PR

**Comment by Batuto** [comment]
#### @moylop260 
##### Now it is ready. Please, can you review this PR?

**Comment by hugho-ad** [comment]
@moylop260 this pr already mergerd makes vauxoo/mexico v10.0 be crashed

image

image

**Comment by hugho-ad** [comment]
@moylop260 here the issue https://github.com/Vauxoo/mexico/issues/675

**Pull request merged**
