### PR TITLE
8.0 #vxt3788 truiz

### PR DESCRIPTION
**Pull request by ruiztulio**
Fixes Vauxoo/instance-vauxoo-com#102
Fixes Vauxoo/instance-vauxoo-com#97

Requested in task 3788

### CODE REVIEW

**Comment by nhomar** [comment]
@josemoralesp can you bless this please in Lodi's enviroment

**Comment by zaoral** [comment]
@nhomar @ruiztulio @JulioSerna this PR also Fix https://github.com/Vauxoo/instance-vauxoo-com/issues/102 correspond to [vx#3776](https://www.vauxoo.com/web?db=vauxoo#id=3776&view_type=form&model=project.task)

**Comment by zaoral** [comment]
@josemoralesp what is missing to merge this PR?

Best Regards

**Comment by josemoralesp** [comment]
@nhomar You can merge this PR

**Pull request merged**
