### PR TITLE
[FIX] security advisory 250716

### PR DESCRIPTION
**Pull request by oscarolar**
This PR includes the update to day of the odoo base branch, the reason of this PR is to update to the most actual changes and to deploy the fixes on the security advisory sent on 20/07/2016 

Dummy for yoytec: https://github.com/Vauxoo/yoytec/pull/1737
Dummy for Instance: https://github.com/Vauxoo/instance/pull/299
Dummy for Lodigroup: https://github.com/Vauxoo/lodigroup/pull/597
Dummy for Pioneer: https://github.com/Vauxoo/pioneer/pull/1
Dummy for Wohlert: https://github.com/Vauxoo/wohlert/pull/71

### CODE REVIEW

**Comment by nhomar** [comment]
@oscarolar Puedes hacer un PR DUMMY a yoytec, lodi's e instance.

**Comment by moylop260** [comment]
@karenkawaii
Could you put a message with instructions to create a dummy PR of odoo, please?

**Comment by KarenKawaii** [comment]
Roger that @moylop260 here you go @oscarolar :
Instructions:
1. Do the following change in the `.travis.yml` file at your dummy project branch:
https://github.com/Vauxoo/yoytec/pull/1611/files
In your case you have to replace `8.0-merge_from_odoo-dev-karen` by `8.0-fix-security-advisory-250716`

Note: The result of this change is only show up in runbot logs.

**Comment by oscarolar** [comment]
Thanks y'all guys, Three dummies created, Lodi, Yoytec and Instance.

**Comment by nhomar** [comment]
On Mon, Jul 25, 2016 at 11:07 AM, Olar Alca [Vauxoo] <
notifications@github.com> wrote:

> Thanks y'all guys, Three dummies created, Lodi, Yoytec and Instance.
>

Lodi represent some other dummies dude.... they are like 6 or 7


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by oscarolar** [comment]
I don't know them all, found that the setup on instance_introspection has the same of this branch: https://github.com/vauxoo/lodigroup, who is the person I have to ask for all the dummies I have to make?

**Comment by nhomar** [comment]
On Mon, Jul 25, 2016 at 11:28 AM, Olar Alca [Vauxoo] <
notifications@github.com> wrote:

> I don't know them all, found that the setup on instance_introspection has
> the same of this branch: https://github.com/vauxoo/lodigroup, who is the
> person I have to ask for all the dummies I have to make?
>

sabrina


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by dsabrinarg** [comment]
@oscarolar @nhomar 
Lodi, Apex and Exim are at Lodigroup repo, only Apex app will be tested on runbot.
The other instances are on repos: ever, ald, wohlert and pioneer. But IMHO just with the dummies for Wohler, Lodigroup and Pioneer It'd be enough.

**Comment by oscarolar** [comment]
thanks @dsabrinarg, as you adviced, dummies updated.

**Comment by oscarolar** [comment]
@moylop260 can you check the errors, yoytec seems to be fine, but I'm not quite familiarized with the other repos.

**Comment by moylop260** [comment]
Runbot is green for yoytec
:+1:

**Comment by moylop260** [comment]
Runbot is yellow for instance (old issue)
+1

Sabrina
Could you check if the log show us a new error from lodi repos?

**Comment by dsabrinarg** [comment]
FYI, I'm waiting for another build @moylop260 @oscarolar I let you know ASAP.

**Comment by josemoralesp** [comment]
Hello all

This [change](https://github.com/Vauxoo/odoo/pull/109/commits/2c19e9be9691ff02e80ddca8cda05ba87fd16550#diff-eedcb99c2a3b66f9db796c8b09a30bcaR47) brings errors in some tests in lodi. I will check the difference to adjust the test for this new change before update our fork of Odoo.

**Comment by oscarolar** [comment]
>Hello all

>This change brings errors in some tests in lodi. I will check the difference to adjust the test for this new change before update our fork of Odoo.

Thank you @josemoralesp

**Pull request closed without merging**
