### PR TITLE
[11.0] Avoid press too many times at same time a button.

### PR DESCRIPTION
**Pull request by moylop260**
Fix big performance issue:
 - https://github.com/odoo/odoo/issues/17280

Commit:
https://github.com/odoo/odoo/commit/39f0895
https://github.com/odoo/odoo/commit/37db390

Avoid press too many times at same time a button.

### CODE REVIEW

**Comment by hugho-ad** [comment]
Is it not possible to request forward port those commits at Odoo/Odoo?

**Comment by moylop260** [comment]
For the record,
They told us that is not possible fowardport it to 11.0
 - https://github.com/odoo/odoo/issues/17280#issuecomment-420273389

But Hugo have created the following issue for 11.5
https://github.com/odoo/odoo/issues/26945

**Comment by hugho-ad** [comment]
@moylop260 
FYI https://github.com/odoo/odoo/issues/26945#event-1859598504 was solved and it works for the scenario that I reported

Regards!

**Comment by moylop260** [comment]
Excellent!
Thanks!
could you backported to 11.0 please?
And try it reproduce it?
Use my current opened pr
-- 
Moisés López Calderón
Mobile: (+521) 477-752-22-30
Twitter: @moylop260
hangout: moylop260@vauxoo.com
http://www.vauxoo.com - Odoo Gold Partner
Twitter: @vauxoo

**Comment by hugho-ad** [comment]
The fix landed at Odoo/enterprise v11.0 https://github.com/odoo/enterprise/commit/762d8235a8cfa5153270f439b899fbdf6d2ec745

**Comment by hugho-ad** [comment]
@moylop260 

I tried to replicate it but apparently was solved since I was not able to replicate it. see the following video
https://youtu.be/VWuTrrIi6K8

Regards!

**Comment by hugho-ad** [comment]
@moylop260 

I made that you told me,

I inherited the read method instead of the search_read, because the search_read never was called, then I set a sleep at confirm_sale and the read, but the system never got block
https://drive.google.com/open?id=1F3DT1zIVNmPobHX2eCx1cvLvQV9OrxEX

Regards!

**Comment by moylop260** [comment]
Ok, let's to closed it for now
If in the future we can reproduce it using other way we will be back here.

**Pull request closed without merging**
