### PR TITLE
[IMP] point_of_sale, pos_coupon: using Odoo helper methods insead of backbones

### PR DESCRIPTION
**Pull request by JVegaB**
Related Odoo PR 

https://github.com/odoo/odoo/pull/103215

### CODE REVIEW

**Comment by hugho-ad** [comment]
why this changes couldn't be target odoo/odoo?

I know they are improvements, but they are not breaking or introducing new behaviors

**Comment by hugho-ad** [comment]
@JVegaB 

I leave you a comment above

**Comment by JVegaB** [comment]
@hugho-ad Just because we are not fixing anything. For me modifications for our convenience, goes into this repo, so the high priority pull request are managed at odoo/odoo.

If I opened a ticket at odoo/odoo, it would say something like: "Changing the lowdash method, for the Odoo one." Giving as excuse, that we have our custom implementation and we need it. So, following that reasoning, I decided to create the pull request here, at vauxoo/odoo.

**Comment by hugho-ad** [comment]
we can try it, at the end it's looks like an not harmful improvement

**Comment by hugho-ad** [comment]
Done at https://github.com/odoo/odoo/commit/9054173b386e39bfd2c5e05304a786a3ea0940f9

**Pull request closed without merging**
