### PR TITLE
[MERGE] Merge from odoo/10.0 to vauxoo/10.0

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by moylop260** [comment]
@dsabrinarg @JulioSerna @suniagajose @luistorresm @osvalr 

We need to upgrade vx/10.0 but we need the dummies PR...

Do you have any customer in production using this branch?
Could you help me to create the dummy pr, please?

**Comment by hugho-ad** [comment]
@moylop260 

You can remove https://github.com/Vauxoo/odoo/commit/df913d1b527182838c6b336204aecebe958053c7 it was fixed in https://github.com/odoo/odoo/commit/7c486b4d0c84c04ac1a42b67484ff3383a69dc28

**Comment by moylop260** [comment]
@hugho-ad 
Done thanks

**Comment by moylop260** [comment]
Manually merged

**Pull request closed without merging**
