### PR TITLE
[FIX] Delete translation of the body_html of mail template 'Email Notification'

### PR DESCRIPTION
**Pull request by egrivero**
This PR is to correct a reported error in the Imeqmo project Vauxoo/imeqmo#30. This error appears when the Spanish language is selected for the system, and an attempt is made to send an email using the "Email Notification" mail template.

I chose to delete the translation in the same way I did in its module.
[mail translation](https://github.com/odoo/odoo/blob/9.0/addons/mail/i18n/es.po#L129)

### CODE REVIEW

**Comment by egrivero** [comment]
Hi @nhomar , here's the PR to remove the translation error of the mail template

**Comment by nhomar** [comment]
Can you make a PR to odoo/odoo also please?

**Comment by nhomar** [comment]
Sorry.. please make a cherry-pick instead a new commit
**2fc0ad8e0ed3e3e17**

**Comment by egrivero** [comment]
@nhomar Ready

**Pull request merged**
