### PR TITLE
[account_anglo_saxon] Avoid difference in price when there is not difference

### PR DESCRIPTION
**Pull request by JulioSerna**
This PR is necessary to avoid issue  with account_anglo_saxon module and difference price

When create PO with price_unit $100 and then confirm -> cancel -> set to draft
and change the price_unit $1, when create invoice from the second picking and validate the invoice create journal item by `price difference` by $99 because invoice_line is getting the first line purchase order line by $100

it was solves with this [commit#6057e64](https://github.com/Vauxoo/odoo/pull/99/commits/6057e645d6724692dbfc287fd650480f007d2028)

### CODE REVIEW

**Comment by JulioSerna** [comment]
@hbto to update vauxoo/odoo this commits will be merged into vauxoo/odoo
could you check them? are related with landed costs

https://github.com/Vauxoo/odoo/pull/99/commits/df212977b8a61bf9fdc7c52acc3bb051f920746d
https://github.com/Vauxoo/odoo/pull/99/commits/214231fbced3ebd99a309a4e64e933946c35f352
https://github.com/Vauxoo/odoo/pull/99/commits/85fd9721494311fc07c5856fe368d81345ce65cf
https://github.com/Vauxoo/odoo/pull/99/commits/bd025cda6a114de1293b583ef0a9fac88ff145b9
https://github.com/Vauxoo/odoo/pull/99/commits/262d98bb6988a4b52ae9eabbe553244ead304d9a
https://github.com/Vauxoo/odoo/pull/99/commits/eb26694e0f30445419e58e88eabae3db1aa18865

@josemoralesp what do you think about this commit?

https://github.com/Vauxoo/odoo/pull/99/commits/d39d191cec76a69cf63b9834e1a99aa87f8be9c4

**Comment by hbto** [comment]
> @hbto to update vauxoo/odoo this commits will be merged into vauxoo/odoo
could you check them? are related with landed costs

df21297
214231f
85fd972
bd025cd
262d98b
eb26694


Checking them

**Comment by hbto** [comment]
@JulioSerna Of all the commits only 214231f affect us directly
though its change is welcome, the remaining ones, do not affect
our implementation of landed_costs, though this trigger in our side
the task to implement them in our code.

df21297 [√] Our implementation should welcome this change.
85fd972 [√] Our implementation should welcome this change.
bd025cd [√] Our implementation should welcome this change.
262d98b [√] Our implementation should welcome this change.
eb26694 [√] Our implementation should welcome this change.


Regards.

**Comment by josemoralesp** [comment]
@JulioSerna 
I am agree with the commit [d39d191](https://github.com/Vauxoo/odoo/pull/99/commits/d39d191cec76a69cf63b9834e1a99aa87f8be9c4) 

:+1:

**Comment by moylop260** [comment]
And the dummies PRs?
FYI https://github.com/Vauxoo/yoytec/issues/1317

**Pull request merged**
