### PR TITLE
[IMP] l10n_mx: Import taxes are supported now

### PR DESCRIPTION
**Pull request by luistorresm**
User Case:
The Company A buy some products from a Foreign Customer, and when they
are received in Mexico, the Broker Partner send an invoice to Company A
by the importation taxes.

In this case, when Company A, make the payment to the broker, the taxes
could be accredited for the company and in your case must be reported in
the DIOT report.

More info about the configuration in the README file.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @hbto 

Do you have news about this PR?

Regards

**Comment by hbto** [comment]
@luistorresm you added a test but do not actually tested that the invoice would have created the journal items according what is needed to report DIOT.

Regards.

**Comment by luistorresm** [comment]
@hbto 

This module (l10n_mx) not have the DIOT report, the test could be added in l10n_mx_enterprise.

What do you think?

Regards

**Comment by hbto** [comment]
:+1:

**Comment by hbto** [comment]
Approved for merge

**Comment by luistorresm** [comment]
Odoo PR https://github.com/odoo/odoo/pull/37815

**Pull request closed without merging**
