### PR TITLE
[IMP] l10n_mx: Updated chart account from v10

### PR DESCRIPTION
**Pull request by luistorresm**
- Only are created the accounts that are necessary to initial data
- Updated tags data
- Improved methods
- Added field in tax.template to allow set the group in taxes created
  with data data

### CODE REVIEW

**Comment by luistorresm** [comment]
@nhomar 

Could you check this PR please?

Regards

**Comment by luistorresm** [comment]
@nhomar 

Sigo en espera de tu revisión para esta PR.

Saludos

**Comment by nhomar** [comment]
Tuvo varios cambios en master de último minuto, ¿los checas antes de este merge pliz.?

**Comment by luistorresm** [comment]
Así es @nhomar 

Si se consideraron.

**Pull request merged**
