### PR TITLE
[MERGE] Merge from odoo/11.0

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@moylop260 

Previous vx/odoo v11.0 updates also need a pr?

This is the first pr that I see to update vx/odoo v11.0

**Comment by moylop260** [comment]
@hugho-ad 
I didn’t get you

**Comment by hugho-ad** [comment]
Previous updates of odoo v11.0 needed a pr?

I thought it was an automatic update without pr

**Comment by dsabrinarg** [comment]
👍 this is need it for task #27430

**Comment by hugho-ad** [comment]
@moylop260 
This can be closed since stable 11.0 branch was updated

Regards!

**Pull request merged**
