### PR TITLE
[FIX][stock_account] Applied changes proposed on PR #4866 from odoo.

### PR DESCRIPTION
**Pull request by amurillo-w**

### CODE REVIEW

**Comment by moylop260** [comment]
This PR wil wait for reply of odoo (in email)

**Comment by moylop260** [comment]
Sorry, ignore my last comment

**Comment by hbto** [comment]
+1,

But this is subject to pass test prior to Merge

**Comment by josemoralesp** [comment]
@hbto The failed with travis is because the process cannot found a .travis.yml file, this file is used to build the test environment. You can go in peace.

**Comment by hbto** [comment]
@ruiztulio please Merge this PR,

Best Regards.

**Pull request merged**
