### PR TITLE
[FIX] Reverting this commit fea667a2433dfc2387daa7051989e840d30e18e0

### PR DESCRIPTION
**Pull request by dsabrinarg**
Fixing Odoo Issue [#21485](https://github.com/odoo/odoo/issues/21485)

### CODE REVIEW

**Comment by nhomar** [comment]
do this to odoo/odoo also please. (relate it to the issue itself).

**Comment by amoyaux** [comment]
Gonna use this instead https://github.com/odoo/odoo/pull/21557/files

**Comment by dsabrinarg** [comment]
Fix proposed by Odoo: PR [#21577](https://github.com/odoo/odoo/pull/21557)

**Comment by dsabrinarg** [comment]
[This](https://github.com/Vauxoo/odoo/pull/256) will be used instead.

**Pull request closed without merging**
