### PR TITLE
[FIX] Translate fields not included in _columns, such as computed fields

### PR DESCRIPTION
**Pull request by hugho-ad**
**Original Issue https://github.com/odoo/odoo/issues/3673**
**Original Pr https://github.com/odoo/odoo/pull/9081**

**https://github.com/Vauxoo/yoytec/pull/992**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@moylop260 
@JulioSerna 
@zaoral
@luistorresm

**Comment by zaoral** [comment]
Excellent +1. @hugho-ad yoi have a dummy pr so we could test it?

**Comment by moylop260** [comment]
+1
Could you add the link with the origin of issue and pr with fix and so on...?

Could you make dummy pr changing .travis.yml file
```diff
     - travis_install_nightly
+    - cd ~/odoo-8.0 && git remote add vauxoo-dev git@github.com:vauxoo-dev/odoo.git && git fetch vauxoo-dev 8.0-translations_fields_not_columns  && git pull vauxoo-dev 8.0-translations_fields_not_columns 
# This change just work with runbot (travis don't support this change)
```

**Comment by zaoral** [comment]
Hi @hugho-ad @moylop260 
What is missing for merge this PR?

I miss the dummy PR when was posted.
I have a perfect candidate to review if this change is working :smile: 
I will related a new dummy PR here so we can test and merge

**Comment by zaoral** [comment]
Test maed in vauxoo/yoytec#1297 was successfully.
Now the translation fields for:

- related fields
- functional fields.

This is a good improve to manage translations

The are translations that are missing:
- when a field help or string change in model definition
- when a selection field option change.
- when a button name change

However I think that the missing translations term export can be done in a future PR

@moylop260 the only thing I was not able to review is what happend with travis lint check build. Because it do not find match for ~/odoo-8.0. Can you help me to configure this branch in order to make the correct review in travis builds?

**Comment by moylop260** [comment]
@nhomar 
Do you have problem to merge it?

**Comment by nhomar** [comment]
@moylop260 

I read the original issues mentioned in the body of this PR but they looks like the solution proposed by odoo was properlly merged, I do not understand the rationale of add this patch.

**Comment by moylop260** [comment]
@nhomar 
Or you are right!
In fact, now this PR has conflicts

@zaoral @hugho-ad @JulioSerna
Could you back here if the error is reproduced again?

**Pull request closed without merging**
