### PR TITLE
odoo: Update Vauxoo/odoo 10.0

### PR DESCRIPTION
**Pull request by egrivero**

### CODE REVIEW

**Comment by egrivero** [comment]
@moylop260 @luistorresm You can do a review and if possible merge of this PR, the Dummies are in green and approved in this [link](https://docs.google.com/spreadsheets/d/1jjW_EnehYrpKeCLKrbDdUggAfQyLz1M90mMdavvFKS0/edit#gid=577086323) you can see.

**Comment by egrivero** [comment]
@moylop260 @luistorresm 
Good morning, if you can check this PR, regards

**Comment by luistorresm** [comment]
@moylop260 

Is related with this PR https://github.com/Vauxoo/enterprise/pull/211

**Comment by moylop260** [comment]
please
merge it with git pull git push

**Comment by luistorresm** [comment]
@egrivero 

I found the next error:

captura de pantalla 2017-10-11 a la s 16 28 41.

this is because you fix this conflict incorrectly
captura de pantalla 2017-10-11 a la s 16 30 12

To test:
1.- Create a new Mexican partner
2.- Assign the an invalid VAT, by example "XXXXX040404FF4"

**Comment by egrivero** [comment]
@luistorresm I'm going to find where the problem comes from.

**Comment by egrivero** [comment]
@luistorresm Make the modification and a test with the error that gave you, show me this

screenshot from 2017-10-12 12 54 26

**Comment by luistorresm** [comment]
Done @egrivero 

Could you close the dummies, please?

Regards

**Comment by egrivero** [comment]
Sure, I'll close the dummies.

**Pull request merged**
