### PR TITLE
8.0 avoid loading order issues truiz

### PR DESCRIPTION
**Pull request by ruiztulio**
@moylop260 I tried to apply the patch but I got an error because some missing files, so I executed a cherry-pick, had to merge some files. All from addons/l10n_hu.

Can you check if all works as espected?

### CODE REVIEW

**Comment by moylop260** [comment]
@ruiztulio 
What is the error caused by `l10n_hu`?

**Comment by moylop260** [comment]
@ruiztulio 
ping

**Comment by ruiztulio** [comment]
@moylop260 no error, just needed to merge files from addons/l10n_hu, I tried again just to double check if any error was shown:

You can see the process (the images are ordered according to the steps I followed):
step 1
step 2
step 3
step 4

**Comment by nhomar** [comment]
This is not valid anymore @ruiztulio @moylop260 if yes please reopen.

**Pull request closed without merging**
