### PR TITLE
[IMP] l10n_mx: Data added to fiscal position to sale & purchase

### PR DESCRIPTION
**Pull request by luistorresm**
Based on [odoo/saas-14](https://github.com/odoo/odoo/blob/saas-14/addons/l10n_mx/data/fiscal_position_data.xml#L34) data.

### CODE REVIEW

**Comment by luistorresm** [comment]
@moylop260 

We need remove from l10n_mx_base, the dependency for l10n_mx.

What do you think about this change?

Regards

**Comment by moylop260** [comment]
Why is required remove this dependency?

**Comment by nhomar** [comment]
On Sat, May 20, 2017 at 1:27 AM, moylop260 <notifications@github.com> wrote:

> Why is required remove this dependency?
>

The chart of account can not be a dependency (as we did in saas-xx) when it
is a dependency in any migrated db the CoA is being tried to be installed
(even if not necessary because it is already loaded) and it is pretty
impossible to load a migrated db.

This use case was tested in abastotal and it demonstrate why l10n_mx was
intentionally excluded as dependency in saas-xx by odoo's team.

Regards.

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by nhomar** [comment]
@luistorresm are you sure any other data is necessary to backport from odoo/odoo?

**Comment by luistorresm** [comment]
@nhomar 

Only this change is requided

**Comment by luistorresm** [comment]
@moylop260 

Could you merge this PR, please?

Regards

**Comment by luistorresm** [comment]
@nhomar 

Could you merge this PR, please?

**Comment by moylop260** [comment]
@luistorresm 
Is valid this PR yet?

**Comment by luistorresm** [comment]
Yes @moylop260 

I will to update this PR,

**Comment by luistorresm** [comment]
Done @moylop260

**Pull request merged**
