### PR TITLE
[REF] l10n_mx: updating account tags nature field issue#153 task#8646

### PR DESCRIPTION
**Pull request by goliveirab**
Account | Nature
---------|--------
119.01 IVA pendiente de pago |  Creditable Account
304.01 Utilidad de ejercicios anteriores | Creditable Account
503.01 Devoluciones, descuentos o bonificaciones sobre compras | Creditable Account
899.01 Otras cuentas de orden | Debitable Account

issue: https://github.com/Vauxoo/enterprise/issues/153

### CODE REVIEW

**Comment by goliveirab** [comment]
@luistorresm @JulioSerna could you please check this.

**Comment by luistorresm** [comment]
@JulioSerna 

Could you approve, to make the correct PR to Odoo?

**Comment by JulioSerna** [comment]
@luistorresm 

should be here or odoo/odoo?

**Comment by luistorresm** [comment]
Was merged in Odoo saas-14.

Thanks @goliveirab 

@JulioSerna 
May be the Thursday this will be applied in saas-17.

Regards

**Pull request closed without merging**
