### PR TITLE
[FIX] account: FX Difference shall not change Invoice residual at reconciliation

### PR DESCRIPTION
**Pull request by moylop260**
Patch of https://github.com/odoo/odoo/pull/32023 to use it from `patches.txt` CI/CD
But without tests in order to reduce conflicts

### CODE REVIEW

**Comment by yaniaular** [comment]
@hbto @moylop260 This branch has conflicts and it's affecting the absa repo. Can you help me to rebase this?

**Comment by moylop260** [comment]
@hbto 
FYI I have created the following backup branch:
 https://github.com/vauxoo-dev/odoo/tree/12.0-vx-pr31257-hbto-moy.bkp1
If you like to review something

@yaniaular 
I just rebase and fixed conflicts.

**Comment by moylop260** [comment]
@hbto 
I saw that https://github.com/odoo/odoo/pull/32023 is merged.
Is this #294 PR valid yet?

**Comment by yaniaular** [comment]
@moylop260,  @hbto Telled me that  This PR and the Odoo's PR are different. By now, with the rebase it's enough

CC @josemoralesp

**Comment by edy1192** [comment]
Hi @hbto @moylop260  This branch has conflicts and it's affecting the absa repo. Can you help me to rebase this?

Thanks. 
cc @yaniaular

**Pull request closed without merging**
